# Generated by Django 5.1.3 on 2024-11-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_alter_category_options_answerblank'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsfolder',
            name='test_blanks',
            field=models.ManyToManyField(blank=True, to='tests.test'),
        ),
    ]
