# Generated by Django 5.1.3 on 2024-11-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_testsfolder_test_blanks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gpa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
