# Generated by Django 4.0.6 on 2024-10-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержание вопроса')),
                ('answer_list', models.JSONField(default=list, verbose_name='Варианты ответов')),
                ('correct_answers', models.JSONField(default=list, verbose_name='Правильные ответы')),
                ('points', models.FloatField(verbose_name='Очки за правильный ответ')),
            ],
        ),
    ]
