# Generated by Django 4.0.6 on 2024-10-21 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название теста')),
                ('description', models.TextField(verbose_name='Описание теста')),
                ('total_points', models.FloatField(verbose_name='Общее количество очков')),
                ('has_timer', models.BooleanField(default=False, verbose_name='Наличие таймера')),
                ('starting_datetime', models.DateTimeField(verbose_name='Дата и время начала теста')),
                ('submission_datetime', models.DateTimeField(verbose_name='Дата и время сдачи теста')),
                ('is_private', models.BooleanField(default=False, verbose_name='Приватный тест')),
                ('entrance_code', models.IntegerField(verbose_name='Код для входа')),
                ('allowed_users', models.ManyToManyField(related_name='allowed_tests', to=settings.AUTH_USER_MODEL, verbose_name='Разрешенные пользователи')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL, verbose_name='Автор теста')),
                ('like', models.ManyToManyField(blank=True, related_name='liked_tests', to=settings.AUTH_USER_MODEL, verbose_name='Лайки')),
                ('question_list', models.ManyToManyField(to='tests.question', verbose_name='Список вопросов')),
                ('test_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.category', verbose_name='Категория теста')),
            ],
        ),
    ]
