# Generated by Django 5.1.1 on 2024-10-22 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_category_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_list',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answers',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='allowed_users',
            field=models.ManyToManyField(related_name='allowed_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='test',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='entrance_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='has_timer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='liked_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='test',
            name='question_list',
            field=models.ManyToManyField(to='tests.question'),
        ),
        migrations.AlterField(
            model_name='test',
            name='starting_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='submission_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.category'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='test',
            name='total_points',
            field=models.FloatField(),
        ),
    ]
