# Generated by Django 5.1.1 on 2024-10-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_alter_category_name_alter_question_answer_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='starting_datetime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='submission_datetime',
            field=models.DateTimeField(blank=True),
        ),
    ]
